"""added default timestamp and source_path

Revision ID: 609e4d00e590
Revises: e0d553da8bfe
Create Date: 2021-05-22 17:39:12.570062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '609e4d00e590'
down_revision = 'e0d553da8bfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bucket_items', sa.Column('source_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bucket_items', 'source_path')
    # ### end Alembic commands ###
