"""added library on top of bucket

Revision ID: e0d553da8bfe
Revises: 88c087ed5e5d
Create Date: 2021-05-22 14:54:10.401686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d553da8bfe'
down_revision = '88c087ed5e5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_libraries_slug'), 'libraries', ['slug'], unique=True)
    op.add_column('buckets', sa.Column('library_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'buckets', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buckets', type_='foreignkey')
    op.drop_column('buckets', 'library_id')
    op.drop_index(op.f('ix_libraries_slug'), table_name='libraries')
    op.drop_table('libraries')
    # ### end Alembic commands ###
